### ISSUE TITLE
Background Colour Of Horizontal Selection List replaces the colour set in story board.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [hightower/HTHorizontalSelectionList#65] opened 2015-12-28 14:01 UTC
I created a view in storyboard with my desired colour. But the horizontal selection list doesn't retain its colour set in story board but is replacing the colour. If we want our preferred colour, our only option is to set it manually.

**Comment by erikackermann** [comment] 2016-01-04 13:42
Closing this as duplicate of this issue: https://github.com/hightower/HTHorizontalSelectionList/issues/64

**Closed by erikackermann** 2016-01-04 13:42 UTC
