### ISSUE TITLE
CartFile Issue

### ISSUE THREAD

**Issue by raj-s** [hightower/HTHorizontalSelectionList#69] opened 2016-02-02 08:06 UTC
Hi,

I am getting below error while using Cartage file,

Skipped building HTHorizontalSelectionList due to the error:
Dependency "HTHorizontalSelectionList" has no shared framework schemes

**Comment by erikackermann** [comment] 2016-02-02 15:28
Hello @raj-s.  I'm not familiar with Carthage but from a quick search it sounds like this issue is caused by the project not having any shared schemes.  Does it fix your issue if you make the HTHorizontalSelectionList scheme shared?

**Comment by bala1801** [comment] 2016-02-03 10:46
Hi Erik,

Thanks for your reply. No, it won't.

As per Carthage's requirement, library should build dynamically rather than static even-though if the schemes are shared.

**Comment by erikackermann** [comment] 2016-02-10 23:00
Sorry for the delayed response.  Can you take a look at the latest on master and see if it fixes your issue?

**Comment by erikackermann** [comment] 2016-11-14 21:17
It appears that it is not possible for this framework to support Carthage.  HTHorizontalSelectionList has one dependency (currently being fetched with cocoapods): M13BadgeView.  This framework is not available via Carthage, and I don't believe there is an easy way for me to make HTHorizontalSelectionList build with Carthage if it's dependencies are not present... let me know if there is a workaround, otherwise I'm to close this issue.

**Closed** 2016-11-15 14:58 UTC
